[2020-05-04 19:44:41,599] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: slack_integration.slack_integration 2020-05-04T17:38:32.190688+00:00 [queued]>
[2020-05-04 19:44:41,608] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: slack_integration.slack_integration 2020-05-04T17:38:32.190688+00:00 [queued]>
[2020-05-04 19:44:41,608] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-05-04 19:44:41,608] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-05-04 19:44:41,608] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-05-04 19:44:41,613] {taskinstance.py:900} INFO - Executing <Task(SlackWebhookOperator): slack_integration> on 2020-05-04T17:38:32.190688+00:00
[2020-05-04 19:44:41,615] {standard_task_runner.py:53} INFO - Started process 7114 to run task
[2020-05-04 19:44:41,652] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: slack_integration.slack_integration 2020-05-04T17:38:32.190688+00:00 [running]> eyrunt-mbp
[2020-05-04 19:44:41,669] {taskinstance.py:1145} ERROR - Invalid URL 'http:///T012TB8A8JJ/B0130CTSXFD/bG6KPnbUxhm9z4uyNZj5nx9c': No host supplied
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/slack_webhook_operator.py", line 113, in execute
    self.hook.execute()
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/hooks/slack_webhook_hook.py", line 152, in execute
    extra_options={'proxies': proxies})
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/http_hook.py", line 135, in run
    prepped_request = session.prepare_request(req)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'http:///T012TB8A8JJ/B0130CTSXFD/bG6KPnbUxhm9z4uyNZj5nx9c': No host supplied
[2020-05-04 19:44:41,679] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=slack_integration, task_id=slack_integration, execution_date=20200504T173832, start_date=20200504T174441, end_date=20200504T174441
[2020-05-04 19:44:51,595] {logging_mixin.py:112} INFO - [2020-05-04 19:44:51,593] {local_task_job.py:103} INFO - Task exited with return code 1
